build_container:
  stage: build
  before_script:
  - docker info
  script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  - TAG=${CI_COMMIT_SHORT_SHA}-$( date -u +%y%m%d%H%M%S )
  - docker build -t "$CI_REGISTRY_USER/odabot:$TAG" .
  - docker push "$CI_REGISTRY_USER/odabot:$TAG"
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  - if: $CI_COMMIT_BRANCH == 'master'
