docker-build:
  stage: build

  image: docker:stable
  services:
  - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""

  before_script:
  - docker info
  - apk add git
  
  script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  - TAG=${CI_COMMIT_SHORT_SHA}-$( date -u +%y%m%d%H%M%S )
  - docker build -t "$CI_REGISTRY_USER/odabot:$TAG" .
  - docker push "$CI_REGISTRY_USER/odabot:$TAG"

  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  - if: $CI_COMMIT_BRANCH == 'master'
