FROM python:3.10

COPY . /source

RUN pip install git+https://github.com/oda-hub/nb2workflow@no-leading-underscore-parameters#egg=nb2workflow[galaxy]
RUN pip install /source[galaxy] && rm -r /source

# Add Tini
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]

RUN useradd jovyan -m --uid 1000
USER 1000

CMD ["odabot", "--settings", "/settings.toml", "make-galaxy-tools", "--loop", "10"]
