[components.frontend]

triggers = [
    ".*frontend.*",
    ".*drupal.*",
    ".*astrooda.*",
]


[components.dispatcher]

triggers = [
    ".*oda_api.*",
    ".*dispatcher.*",
]

[nb2workflow]

k8s_namespace = "oda-staging"
dispatcher = {url = "https://dispatcher-staging.obsuks1.unige.ch", deployment = "oda-dispatcher"}
kb = {type = "odakb"}
frontend = {instruments_dir = "/frontend-instruments/", deployment = "oda-frontend"}
registry = "odahub"
build_engine = "docker"
state_storage = {type = "yaml", path = '/oda-bot-runtime-workflows.yaml'}
