[components.frontend]

triggers = [
    ".*frontend.*",
    ".*drupal.*",
    ".*astrooda.*",
]


[components.dispatcher]

triggers = [
    ".*oda_api.*",
    ".*dispatcher.*",
]

[nb2workflow]

k8s_namespace = "oda-staging"
dispatcher = {url = "https://dispatcher-staging.obsuks1.unige.ch", deployment = "oda-dispatcher"}
kb = {type = "odakb"}
frontend = {instruments_dir = "/frontend-instruments/", deployment = "oda-frontend"}
registry = "odahub"
build_engine = "docker"
state_storage = {type = "yaml", path = '/oda-bot-runtime-workflows.yaml'}

[nb2galaxy]

tools_repo = "https://github.com/dsavchenko/tools-astro.git"
target_branch = 'main'
target_tools_repo = "https://github.com/esg-epfl-apc/tools-astro.git"
repo_cache_path = "/nb2galaxy-cache"
state_storage = "/oda-bot-runtime-galaxy.yaml"
git_identity = {name = "ODA bot", email = "noreply@odahub.io"}
git_credentials = "/.git-credentials"